sudo: required
services:
  - docker

before_install:
  - docker build -t complex/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run complex/react-test npm run testCI

after_success:
  - docker build -t rafaelsm/docker-client ./client
  - docker build -t rafaelsm/docker-nginx ./nginx
  - docker build -t rafaelsm/docker-server ./server
  - docker build -t rafaelsm/docker-worker ./worker
  #login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push rafaelsm/docker-client
  - docker push rafaelsm/docker-nginx
  - docker push rafaelsm/docker-server
  - docker push rafaelsm/docker-worker
