sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t complex/docker-client ./client
  - docker build -t complex/docker-nginx ./nginx
  - docker build -t complex/docker-server ./server
  - docker build -t complex/docker-worker ./worker
  #login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push complex/docker-client
  - docker push complex/docker-nginx
  - docker push complex/docker-server
  - docker push complex/docker-worker
